try {
    console.log(nãoExisto)
} catch(err){
    console.log("essa variavel não existe")
}